Feat/program secondary card with score star row and marketing label
urfit-tech/lodestar-app-element pull request #115
Opened 2024-11-17 12:05 UTC by Logos50607

feat: program secondary card with score star row and marketing label

2024-11-17 12:06 UTC, Logos50607 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【課程管理】新增行銷標籤欄位及可選擇樣式](https://trello.com/c/rbFpO0MB/5540-2%E3%80%90%E8%AA%B2%E7%A8%8B%E7%AE%A1%E7%90%86%E3%80%91%E6%96%B0%E5%A2%9E%E8%A1%8C%E9%8A%B7%E6%A8%99%E7%B1%A4%E6%AC%84%E4%BD%8D%E5%8F%8A%E5%8F%AF%E9%81%B8%E6%93%87%E6%A8%A3%E5%BC%8F)

2024-11-17 12:06 UTC, Logos50607 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1)【頁面模組】課程元件樣式二新增評價星及行銷標籤的呈現](https://trello.com/c/6eTmOjk2/5636-1%E3%80%90%E9%A0%81%E9%9D%A2%E6%A8%A1%E7%B5%84%E3%80%91%E8%AA%B2%E7%A8%8B%E5%85%83%E4%BB%B6%E6%A8%A3%E5%BC%8F%E4%BA%8C%E6%96%B0%E5%A2%9E%E8%A9%95%E5%83%B9%E6%98%9F%E5%8F%8A%E8%A1%8C%E9%8A%B7%E6%A8%99%E7%B1%A4%E7%9A%84%E5%91%88%E7%8F%BE)

2024-11-22 07:12 UTC, LoisChen68 requested changes

2024-11-22 07:26 UTC, LoisChen68 commented on src/hooks/review.ts
> +      }
Must be camelcase, start with uppercase.

2024-11-27 07:37 UTC, LoisChen68 approved these changes

2024-11-27 07:37 UTC, merged