Bugfix/modify checkout process
urfit-tech/lodestar-app-element pull request #35
Opened 2022-07-04 08:14 UTC by HLTVProxy

- modify CheckoutProductModel for merchandise purchase
- also need to watch other repos which are app, admin and backend

2022-07-04 08:26 UTC, HLTVProxy commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) 【商品】商品希望也能用代幣購買 [1]](https://trello.com/c/IN2yZDyB/3475-3-%E3%80%90%E5%95%86%E5%93%81%E3%80%91%E5%95%86%E5%93%81%E5%B8%8C%E6%9C%9B%E4%B9%9F%E8%83%BD%E7%94%A8%E4%BB%A3%E5%B9%A3%E8%B3%BC%E8%B2%B7-1)

2022-07-06 06:13 UTC, Ponchimeow commented on src/components/modals/CheckoutProductModal.tsx
> +            defaultProductId !== undefined && defaultProductId.includes('MerchandiseSpec_')
NITS: can reduce it to `defaultProductId?.includes('MerchandiseSpec_') ? '' : `(${quantity * saleAmount} 張)`  `

2022-07-06 06:34 UTC, Ponchimeow commented on src/components/modals/CheckoutProductModal.tsx
> +              {isCoinsEnough ? <PriceLabel listPrice={totalPrice} /> : `${settings['coin.unit']} 不足`}
if settings['coin.unit'] is not set in hasura, it will be error

2022-07-06 06:37 UTC, Ponchimeow requested changes
settings['coin.unit'] need to be fix

2022-07-11 07:59 UTC, Ponchimeow approved these changes

2022-07-11 08:00 UTC, merged